---
- name: Create VLAN if do'nt exist on a Cisco switch
  hosts: sw1-core
  gather_facts: no
  connection: local
    
  vars:
    vlan_id: 10
    vlan_name: admin-sys
    interface: GigabitEthernet1/0/1

  tasks:
    - name: T1 - Collect facts about VLAN "{{ vlan_id }}" on device
      ios_command:
        commands: show vlan id "{{ vlan_id }}" | include enet
      register: sh_vlan_output
      
    - name: T2 - show if the vlan exist
      debug:
        var: sh_vlan_output

    - name: T3 - Check if VLAN is defined and does not do anything if existing
      set_fact:
        vlan_exists: false
      when: sh_vlan_output.stdout_lines is defined

    - name: T4 - Check if VLAN is undefined and if not then go for below task to Add VLAN
      set_fact:
        vlan_exists: true
      when: sh_vlan_output.stdout_lines is undefined

    - name: T5 - Add VLAN using aggregate
      ios_vlan:
        aggregate:
        - {vlan_id: "{{ vlan_id }}", name: "{{ vlan_name }}", interfaces: "{{ interface }}"}

    - name: T6 - Collect facts about VLAN "{{ vlan_id }}" on device
      ios_command:
        commands: show vlan id "{{ vlan_id }}" | include enet
      register: sh_vlan_output2

    - name: T7 - show if the vlan exist
      debug:
        var: sh_vlan_output2

