---
- name: "collect device facts"
  hosts: network
  tasks:
    - name: "gather device facts"
      ios_facts:
      register: device_facts

    - name: "write Device Facts"
      blockinfile:
        path: ../facts.yml
        create: yes
        block: |
          device_facts:
          {% for host in play_hosts %}
          {% set node = hostvars[host] %}
            {{ node.ansible_net_hostname }}:
              serial_number: {{ node.ansible_net_serialnum }}
              ios_version: {{ node.ansible_net_version }}
              device_model: {{ node.ansible_net_model }}
              image_name: {{ node.ansible_net_image }}
          {% endfor %}
      run_once: yes
      delegate_to: localhost

